import React from 'react';
import Select from 'react-select';

const level3options = [
    {value: 'Burgas_rest', label: 'Burgas_rest'},
    {value: 'Aheloy', label: 'Aheloy'},
    {value: 'Ahtopol', label: 'Ahtopol'},
    {value: 'Aytos', label: 'Aytos'},
    {value: 'Burgas', label: 'Burgas'},
    {value: 'Kameno', label: 'Kameno'},
    {value: 'Karnobat', label: 'Karnobat'},
    {value: 'Kiten', label: 'Kiten'},
    {value: 'Malko Tarnovo', label: 'Malko Tarnovo'},
    {value: 'Nesebar', label: 'Nesebar'},
    {value: 'Obzor', label: 'Obzor'},
    {value: 'Primorsko', label: 'Primorsko'},
    {value: 'Sozopol', label: 'Sozopol'},
    {value: 'Sredets', label: 'Sredets'},
    {value: 'Sungurlare', label: 'Sungurlare'},
    {value: 'Sveti Vlas', label: 'Sveti Vlas'},
    {value: 'Tsarevo', label: 'Tsarevo'},
    {value: 'Asenovgrad', label: 'Asenovgrad'},
    {value: 'Banya', label: 'Banya'},
    {value: 'Brezovo', label: 'Brezovo'},
    {value: 'Hisarya', label: 'Hisarya'},
    {value: 'Kalofer', label: 'Kalofer'},
    {value: 'Karlovo', label: 'Karlovo'},
    {value: 'Klisura', label: 'Klisura'},
    {value: 'Krichim', label: 'Krichim'},
    {value: 'Kuklen', label: 'Kuklen'},
    {value: 'Parvomay', label: 'Parvomay'},
    {value: 'Perushtitsa', label: 'Perushtitsa'},
    {value: 'Plovdiv', label: 'Plovdiv'},
    {value: 'Rakovski', label: 'Rakovski'},
    {value: 'Sadovo', label: 'Sadovo'},
    {value: 'Saedinenie', label: 'Saedinenie'},
    {value: 'Sopot', label: 'Sopot'},
    {value: 'Stamboliyski', label: 'Stamboliyski'},
    {value: 'Plovdiv_rest', label: 'Plovdiv_rest'},
    {value: 'Borovets Resort', label: 'Borovets Resort'},
    {value: 'Botevgrad', label: 'Botevgrad'},
    {value: 'Bozhurishte', label: 'Bozhurishte'},
    {value: 'Dolna banya', label: 'Dolna banya'},
    {value: 'Dragoman', label: 'Dragoman'},
    {value: 'Elin Pelin', label: 'Elin Pelin'},
    {value: 'Etropole', label: 'Etropole'},
    {value: 'Ihtiman', label: 'Ihtiman'},
    {value: 'Kostenets', label: 'Kostenets'},
    {value: 'Kostinbrod', label: 'Kostinbrod'},
    {value: 'Pirdop', label: 'Pirdop'},
    {value: 'Pravets', label: 'Pravets'},
    {value: 'Varna', label: 'Varna'},
    {value: 'Varna North Resort', label: 'Varna North Resort'},
    {value: 'Varna South Resort', label: 'Varna South Resort'},
    {value: 'Varna_rest', label: 'Varna_rest'},
    {value: 'Panagyurishte', label: 'Panagyurishte'},
    {value: 'Pazardzhik', label: 'Pazardzhik'},
    {value: 'Peshtera', label: 'Peshtera'},
    {value: 'Rakitovo', label: 'Rakitovo'},
    {value: 'Sarnitsa', label: 'Sarnitsa'},
    {value: 'Septemvri', label: 'Septemvri'},
    {value: 'Strelcha', label: 'Strelcha'},
    {value: 'Velingrad', label: 'Velingrad'},
    {value: 'Vetren', label: 'Vetren'},
    {value: 'Pazardzhik_rest', label: 'Pazardzhik_rest'},
    {value: 'Dimitrovgrad', label: 'Dimitrovgrad'},
    {value: 'Harmanli', label: 'Harmanli'},
    {value: 'Haskovo', label: 'Haskovo'},
    {value: 'Lyubimets', label: 'Lyubimets'},
    {value: 'Merichleri', label: 'Merichleri'},
    {value: 'Simeonovgrad', label: 'Simeonovgrad'},
    {value: 'Svilengrad', label: 'Svilengrad'},
    {value: 'Haskovo_rest', label: 'Haskovo_rest'},
    {value: 'Berkovitsa', label: 'Berkovitsa'},
    {value: 'Boychinovtsi', label: 'Boychinovtsi'},
    {value: 'Brusartsi', label: 'Brusartsi'},
    {value: 'Lom', label: 'Lom'},
    {value: 'Montana', label: 'Montana'},
    {value: 'Varshets', label: 'Varshets'},
    {value: 'Montana_rest', label: 'Montana_rest'},
    {value: 'Letnitsa', label: 'Letnitsa'},
    {value: 'Lovech', label: 'Lovech'},
    {value: 'Lukovit', label: 'Lukovit'},
    {value: 'Teteven', label: 'Teteven'},
    {value: 'Troyan', label: 'Troyan'},
    {value: 'Yablanitsa', label: 'Yablanitsa'},
    {value: 'Lovech_rest', label: 'Lovech_rest'},
    {value: 'Chirpan', label: 'Chirpan'},
    {value: 'Gurkovo', label: 'Gurkovo'},
    {value: 'Kazanlak', label: 'Kazanlak'},
    {value: 'Maglizh', label: 'Maglizh'},
    {value: 'Radnevo', label: 'Radnevo'},
    {value: 'Stara Zagora', label: 'Stara Zagora'},
    {value: 'Stara Zagora_rest', label: 'Stara Zagora_rest'},
    {value: 'Chepelare', label: 'Chepelare'},
    {value: 'Devin', label: 'Devin'},
    {value: 'Rudozem', label: 'Rudozem'},
    {value: 'Smolyan', label: 'Smolyan'},
    {value: 'Pamporovo Resort', label: 'Pamporovo Resort'},
    {value: 'Dobrich_rest', label: 'Dobrich_rest'},
    {value: 'Balchik', label: 'Balchik'},
    {value: 'Dobrich', label: 'Dobrich'},
    {value: 'General Toshevo', label: 'General Toshevo'},
    {value: 'Shabla', label: 'Shabla'},
    {value: 'Batanovtsi', label: 'Batanovtsi'},
    {value: 'Pernik', label: 'Pernik'},
    {value: 'Radomir', label: 'Radomir'},
    {value: 'Tran', label: 'Tran'},
    {value: 'Pernik_rest', label: 'Pernik_rest'},
    {value: 'Kaspichan', label: 'Kaspichan'},
    {value: 'Novi pazar', label: 'Novi pazar'},
    {value: 'Shumen', label: 'Shumen'},
    {value: 'Smyadovo', label: 'Smyadovo'},
    {value: 'Shumen_rest', label: 'Shumen_rest'},
    {value: 'Bolyarovo', label: 'Bolyarovo'},
    {value: 'Elhovo', label: 'Elhovo'},
    {value: 'Straldzha', label: 'Straldzha'},
    {value: 'Yambol', label: 'Yambol'},
    {value: 'Yambol_rest', label: 'Yambol_rest'},
    {value: 'Antonovo', label: 'Antonovo'},
    {value: 'Omurtag', label: 'Omurtag'},
    {value: 'Popovo', label: 'Popovo'},
    {value: 'Targovishte', label: 'Targovishte'},
    {value: 'Targovishte_rest', label: 'Targovishte_rest'},
    {value: 'Nova Zagora', label: 'Nova Zagora'},
    {value: 'Shivachevo', label: 'Shivachevo'},
    {value: 'Sliven', label: 'Sliven'},
    {value: 'Tvarditsa', label: 'Tvarditsa'},
    {value: 'Sliven_rest', label: 'Sliven_rest'},
    {value: 'Sofia', label: 'Sofia'},
    {value: 'Burgas North Resort', label: 'Burgas North Resort'},
    {value: 'Burgas South Resort', label: 'Burgas South Resort'},
    {value: 'Samokov', label: 'Samokov'},
    {value: 'Slivnitsa', label: 'Slivnitsa'},
    {value: 'Svoge', label: 'Svoge'},
    {value: 'Zlatitsa', label: 'Zlatitsa'},
    {value: 'Sofia Region_rest', label: 'Sofia Region_rest'},
    {value: 'Belene', label: 'Belene'},
    {value: 'Cherven bryag', label: 'Cherven bryag'},
    {value: 'Dolna Mitropolia', label: 'Dolna Mitropolia'},
    {value: 'Dolni Dabnik', label: 'Dolni Dabnik'},
    {value: 'Gulyantsi', label: 'Gulyantsi'},
    {value: 'Knezha', label: 'Knezha'},
    {value: 'Koynare', label: 'Koynare'},
    {value: 'Levski', label: 'Levski'},
    {value: 'Pleven', label: 'Pleven'},
    {value: 'Pordim', label: 'Pordim'},
    {value: 'Slavyanovo', label: 'Slavyanovo'},
    {value: 'Trastenik', label: 'Trastenik'},
    {value: 'Pleven_rest', label: 'Pleven_rest'},
    {value: 'Byala cherkva', label: 'Byala cherkva'},
    {value: 'Dolna Oryahovitsa', label: 'Dolna Oryahovitsa'},
    {value: 'Gorna Oryahovitsa', label: 'Gorna Oryahovitsa'},
    {value: 'Lyaskovets', label: 'Lyaskovets'},
    {value: 'Pavlikeni', label: 'Pavlikeni'},
    {value: 'Polski Trambesh', label: 'Polski Trambesh'},
    {value: 'Strazhitsa', label: 'Strazhitsa'},
    {value: 'Suhindol', label: 'Suhindol'},
    {value: 'Svishtov', label: 'Svishtov'},
    {value: 'Veliko Tarnovo', label: 'Veliko Tarnovo'},
    {value: 'Zlataritsa', label: 'Zlataritsa'},
    {value: 'Veliko Tarnovo_rest', label: 'Veliko Tarnovo_rest'},
    {value: 'Bansko Resort', label: 'Bansko Resort'},
    {value: 'Blagoevgrad_rest', label: 'Blagoevgrad_rest'},
    {value: 'Bansko', label: 'Bansko'},
    {value: 'Belitsa', label: 'Belitsa'},
    {value: 'Blagoevgrad', label: 'Blagoevgrad'},
    {value: 'Gotse Delchev', label: 'Gotse Delchev'},
    {value: 'Petrich', label: 'Petrich'},
    {value: 'Razlog', label: 'Razlog'},
    {value: 'Sandanski', label: 'Sandanski'},
    {value: 'Simitli', label: 'Simitli'},
    {value: 'Yakoruda', label: 'Yakoruda'},
    {value: 'Aksakovo', label: 'Aksakovo'},
    {value: 'Dalgopol', label: 'Dalgopol'},
    {value: 'Devnya', label: 'Devnya'},
    {value: 'Dolni chiflik', label: 'Dolni chiflik'},
    {value: 'Provadia', label: 'Provadia'},
    {value: 'Suvorovo', label: 'Suvorovo'},
    {value: 'Valchi dol', label: 'Valchi dol'},
    {value: 'Smolyan_rest', label: 'Smolyan_rest'},
    {value: 'Ardino', label: 'Ardino'},
    {value: 'Dzhebel', label: 'Dzhebel'},
    {value: 'Kardzhali', label: 'Kardzhali'},
    {value: 'Krumovgrad', label: 'Krumovgrad'},
    {value: 'Momchilgrad', label: 'Momchilgrad'},
    {value: 'Kardzhali_rest', label: 'Kardzhali_rest'},
    {value: 'Bobov dol', label: 'Bobov dol'},
    {value: 'Dupnitsa', label: 'Dupnitsa'},
    {value: 'Kocherinovo', label: 'Kocherinovo'},
    {value: 'Kyustendil', label: 'Kyustendil'},
    {value: 'Sapareva banya', label: 'Sapareva banya'},
    {value: 'Kyustendil_rest', label: 'Kyustendil_rest'},
    {value: 'Byala Slatina', label: 'Byala Slatina'},
    {value: 'Kozloduy', label: 'Kozloduy'},
    {value: 'Oryahovo', label: 'Oryahovo'},
    {value: 'Roman', label: 'Roman'},
    {value: 'Vratsa', label: 'Vratsa'},
    {value: 'Vratsa_rest', label: 'Vratsa_rest'},
    {value: 'Belogradchik', label: 'Belogradchik'},
    {value: 'Bregovo', label: 'Bregovo'},
    {value: 'Dunavtsi', label: 'Dunavtsi'},
    {value: 'Kula', label: 'Kula'},
    {value: 'Vidin', label: 'Vidin'},
    {value: 'Vidin_rest', label: 'Vidin_rest'},
    {value: 'Gabrovo_rest', label: 'Gabrovo_rest'},
    {value: 'Dryanovo', label: 'Dryanovo'},
    {value: 'Gabrovo', label: 'Gabrovo'},
    {value: 'Plachkovtsi', label: 'Plachkovtsi'},
    {value: 'Sevlievo', label: 'Sevlievo'},
    {value: 'Tryavna', label: 'Tryavna'},
    {value: 'Isperih', label: 'Isperih'},
    {value: 'Kubrat', label: 'Kubrat'},
    {value: 'Loznitsa', label: 'Loznitsa'},
    {value: 'Razgrad', label: 'Razgrad'},
    {value: 'Zavet', label: 'Zavet'},
    {value: 'Razgrad_rest', label: 'Razgrad_rest'},
    {value: 'Borovo', label: 'Borovo'},
    {value: 'Byala', label: 'Byala'},
    {value: 'Glodzhevo', label: 'Glodzhevo'},
    {value: 'Marten', label: 'Marten'},
    {value: 'Ruse', label: 'Ruse'},
    {value: 'Ruse_rest', label: 'Ruse_rest'},
    {value: 'Dulovo', label: 'Dulovo'},
    {value: 'Glavinitsa', label: 'Glavinitsa'},
    {value: 'Silistra', label: 'Silistra'},
    {value: 'Tutrakan', label: 'Tutrakan'},
    {value: 'Silistra_rest', label: 'Silistra_rest'},

]
const level2options = [
    {value: 'Burgas_Region', label: 'Burgas_Region'},
    {value: 'Plovdiv_Region', label: 'Plovdiv_Region'},
    {value: 'Sofia Region', label: 'Sofia Region'},
    {value: 'Pleven_Region', label: 'Pleven_Region'},
    {value: 'Veliko Tarnovo_Region', label: 'Veliko Tarnovo_Region'},
    {value: 'Blagoevgrad_Region', label: 'Blagoevgrad_Region'},
    {value: 'Varna_Region', label: 'Varna_Region'},
    {value: 'Pazardzhik_Region', label: 'Pazardzhik_Region'},
    {value: 'Haskovo_Region', label: 'Haskovo_Region'},
    {value: 'Montana_Region', label: 'Montana_Region'},
    {value: 'Lovech_Region', label: 'Lovech_Region'},
    {value: 'Stara Zagora_Region', label: 'Stara Zagora_Region'},
    {value: 'Smolyan_Region', label: 'Smolyan_Region'},
    {value: 'Kardzhali_Region', label: 'Kardzhali_Region'},
    {value: 'Kyustendil_Region', label: 'Kyustendil_Region'},
    {value: 'Vratsa_Region', label: 'Vratsa_Region'},
    {value: 'Vidin_Region', label: 'Vidin_Region'},
    {value: 'Gabrovo_Region', label: 'Gabrovo_Region'},
    {value: 'Razgrad_Region', label: 'Razgrad_Region'},
    {value: 'Ruse_Region', label: 'Ruse_Region'},
    {value: 'Silistra_Region', label: 'Silistra_Region'},
    {value: 'Dobrich_Region', label: 'Dobrich_Region'},
    {value: 'Pernik_Region', label: 'Pernik_Region'},
    {value: 'Shumen_Region', label: 'Shumen_Region'},
    {value: 'Yambol_Region', label: 'Yambol_Region'},
    {value: 'Targovishte_Region', label: 'Targovishte_Region'},
    {value: 'Sliven_Region', label: 'Sliven_Region'},
    {value: 'Sofia', label: 'Sofia'},
]

const newOptions = [
    {
        label: 'Level 2',
        options: level2options,
    },
    {
        label: 'Level 3',
        options: level3options,
    },
]

const groupStyles = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
};
const groupBadgeStyles = {
    backgroundColor: '#EBECF0',
    borderRadius: '2em',
    color: '#172B4D',
    display: 'inline-block',
    fontSize: 12,
    fontWeight: 'normal',
    lineHeight: '1',
    minWidth: 1,
    padding: '0.16666666666667em 0.5em',
    textAlign: 'center',
};

const formatGroupLabel = data => (
    <div style={groupStyles}>
        <span>{data.label}</span>
        <span style={groupBadgeStyles}>{data.options.length}</span>
    </div>
);

export default function selectRegionComponent() {
    return (<Select
                name="region"
                closeMenuOnSelect={true}
                isSearchable={true}
                isClearable={true}
                options={newOptions}
                className="selectRegion"
                classNamePrefix="select"
                placeholder="Click here to select something"
                defaultValue={null}
                formatGroupLabel={formatGroupLabel}
                required={true}
            />)
}