const level0options = [
    {level: 0, father: 'Network', label: 'CS'},
    {level: 0, father: 'Network', label: 'PS'},
]
const level1options = [
    {level: 1, father: 'CS', label: 'Voice'},
    {level: 1, father: 'CS', label: 'SMS'},
    {level: 1, father: 'PS', label: 'WEB'},
    {level: 1, father: 'PS', label: 'Video_Streaming'},
    {level: 1, father: 'PS', label: 'IM'},
    {level: 1, father: 'PS', label: 'File_Transfer'},
]
const level2options = [
    {level: 2, father: 'SMS', label: 'SMS_Delay_ms'},
    {level: 2, father: 'SMS', label: 'SMS_Service_Availability'},
    {level: 2, father: 'Voice', label: 'Call_Setup_Success_Rate'},
    {level: 2, father: 'Voice', label: 'Call_Completion_Failure_Rate'},
    {level: 2, father: 'Voice', label: 'Call_Setup_Time'},
    {level: 2, father: 'WEB', label: 'WEB_Browsing_Integrity'},
    {level: 2, father: 'WEB', label: 'WEB_Browsing_Retainability'},
    {level: 2, father: 'Video_Streaming', label: 'Video_Streaming_Integrity'},
    {level: 2, father: 'Video_Streaming', label: 'Video_Streaming_Retainability'},
    {level: 2, father: 'IM', label: 'IM_Integrity'},
    {level: 2, father: 'IM', label: 'IM_Retainability'},
    {level: 2, father: 'File_Transfer', label: 'File_Sharing_Integrity'},
    {level: 2, father: 'File_Transfer', label: 'File_Sharing_Retainability'},
    {level: 2, father: 'File_Transfer', label: 'Multimedia_Integrity'},
]
const level3options = [
    {level: 3, father: 'SMS_Delay', label: 'SMS_Origination_Delay_ms'},
    {level: 3, father: 'SMS_Delay', label: 'SMS_Termination_Delay_ms'},
    {level: 3, father: 'SMS_Service_Availability', label: 'SMS_Termination_Rate'},
    {level: 3, father: 'SMS_Service_Availability', label: 'SMS_Origination_Success_Rate'},
    {level: 3, father: 'Call_Setup_Success_Rate', label: 'Perceived_Call_Success_Rate'},
    {level: 3, father: 'Call_Setup_Success_Rate', label: 'VoLTE_MO_Network_Connection_Rate'},
    {level: 3, father: 'Call_Setup_Success_Rate', label: 'VoWiFi_MO_Connection_Rate'},
    {level: 3, father: 'Call_Completion_Failure_Rate', label: 'Perceived_Call_Drop_Rate'},
    {level: 3, father: 'Call_Completion_Failure_Rate', label: 'VoLTE_Call_Drop_Rate'},
    {level: 3, father: 'Call_Completion_Failure_Rate', label: 'VoWiFi_MO_Call_Drop_Rate'},
    {level: 3, father: 'Call_Setup_Time', label: 'E2E_Call_Connection_Delay_ms'},
    {level: 3, father: 'Call_Setup_Time', label: 'V2V_MO_Connection_Delay'},
    {level: 3, father: 'Call_Setup_Time', label: 'VoWiFi_MO_Connection_Delay_ms'},
    {level: 3, father: 'Call_Setup_Time', label: 'VoLTE_to_VoLTE_Voice_MOS'},
    {level: 3, father: 'WEB_Browsing_Retainability', label: 'Page_UL_TCP_Retransmission_Rate'},
    {level: 3, father: 'WEB_Browsing_Retainability', label: 'Page_DL_TCP_Retransmission_Rate'},
    {level: 3, father: 'WEB_Browsing_Integrity', label: 'Page_Server_Side_RTT'},
    {level: 3, father: 'WEB_Browsing_Integrity', label: 'Page_Client_Side_RTT'},
    {level: 3, father: 'WEB_Browsing_Integrity', label: 'Page_E2E_Delay'},
    {level: 3, father: 'WEB_Browsing_Integrity', label: 'Page_Response_Delay_ms'},
    {level: 3, father: 'WEB_Browsing_Integrity', label: 'Page_DL_Throughput_Kbps'},
    {level: 3, father: 'Video_Streaming_Retainability', label: 'Video_Stream_DL_TCP_Retransmission_Rate'},
    {level: 3, father: 'Video_Streaming_Retainability', label: 'Video_Stream_UL_TCP_Retransmission_Rate'},
    {level: 3, father: 'Video_Streaming_Integrity', label: 'Video_Streaming_xKB_Start_Delay'},
    {level: 3, father: 'Video_Streaming_Integrity', label: 'Video_Stream_Client_Side_Round_Trip_Time_ms'},
    {level: 3, father: 'Video_Streaming_Integrity', label: 'Video_Stream_E2E_Delay'},
    {level: 3, father: 'Video_Streaming_Integrity', label: 'Video_Stream_Server_Side_Round_Trip_Time_ms'},
    {level: 3, father: 'Video_Streaming_Integrity', label: 'Video_Streaming_Download_Throughput_Kbps'},
    {level: 3, father: 'IM_Retainability', label: 'IM_DL_TCP_Packets_Loss_Rate'},
    {level: 3, father: 'IM_Retainability', label: 'IM_UL_TCP_Packets_Loss_Rate'},
    {level: 3, father: 'IM_Integrity', label: 'IM_Interacting_Delay'},
    {level: 3, father: 'IM_Integrity', label: 'IM_Server_Side_Round_Trip_Time_ms'},
    {level: 3, father: 'IM_Integrity', label: 'IM_Client_Side_Round_Trip_Time_ms'},
    {level: 3, father: 'File_Sharing_Retainability', label: 'File_Access_Server_Side_Uplink_TCP_Packet_Loss_Rate'},
    {level: 3, father: 'File_Sharing_Retainability', label: 'File_Access_Server_Side_Downlink_TCP_Packet_Loss_Rate'},
    {level: 3, father: 'File_Sharing_Retainability', label: 'File_Access_Client_Side_Uplink_TCP_Packet_Loss_Rate'},
    {level: 3, father: 'File_Sharing_Retainability', label: 'File_Access_Client_Side_Downlink_TCP_Packet_Loss_Rate'},
    {level: 3, father: 'File_Sharing_Integrity', label: 'File_Sharing_Response_Delay'},
    {level: 3, father: 'File_Sharing_Integrity', label: 'File_Sharing_UL_Throughput_Kbps'},
    {level: 3, father: 'File_Sharing_Integrity', label: 'File_Sharing_DL_Throughput_Kbps'},
    {level: 3, father: 'Multimedia_Integrity', label: 'Multimedia_Response_Delay'},
    {level: 3, father: 'Multimedia_Integrity', label: 'Multimedia_UL_Throughput_Kbps'},
    {level: 3, father: 'Multimedia_Integrity', label: 'Multimedia_DL_Throughput_Kbps'},
]

